name: Testing

on:
  push:
  pull_request:

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: jirutka/setup-alpine@v1
        with:
          branch: v3.15

      - name: install deps
        run: apk add gcc libc-dev pcre pcre-dev

      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4 # action page: <https://github.com/actions/setup-go>
        with:
          go-version: stable

      - name: Install Go dependencies
        run: go mod download

      - name: Run linter
        uses: golangci/golangci-lint-action@v3.7.0
        with:
          version: v1.55.2 # without patch version
          only-new-issues: false # show only new issues if it's a pull request
          args: -v --build-tags=race --timeout=10m
