name: update github action config

permissions: write-all

on:
  push:
    branches:
      - master

jobs:
  update-ga-config:
    runs-on: ubuntu-latest
    steps:
      - name: install deps
        run: sudo apt install gcc

      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4 # action page: <https://github.com/actions/setup-go>
        with:
          go-version: stable

      - name: Install Go dependencies
        run: go mod download

      - name: Configure git user
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Hash prev version
        id: prev_version
        run: echo "hash=${{ hashFiles('action.yaml') }}" >> $GITHUB_OUTPUT

      - name: Generate new config file
        run: |
          go run ./cmd/main.go --singlecli-codegen-ga

      - name: Commit changes
        if: ${{ steps.prev_version.outputs.hash != hashFiles('action.yaml') }}
        run: |
          git add action.yaml
          git commit -m "chore: actualize ga config"
          git push
